# Generated by Django 4.0.5 on 2024-01-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_address_order_latitude_order_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('COOKING', 'Cooking'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered')], default='NEW', max_length=20),
        ),
    ]
